version: '{build}'

environment:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

build_script:
  - npm pack --silent
  - bash -c "npm install -g *.tgz"

artifacts:
  - path: '*.tgz'

test_script:
  - npm install fuse-sdk -g
  - uno build android app
