os:
  - linux
  - osx

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew cask uninstall java # uninstall java9
        brew tap caskroom/versions
        brew cask install java8 # install java8
    fi

script:
  - npm install
